version: '3.8'

services:
  n8n:
    image: n8nio/n8n:latest
    container_name: n8n_core_app
    ports:
      - "5678:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - N8N_DB=mongodb
      - N8N_DB_MONGODB_URL=mongodb://admin:minhaSenhaForte123@n8n_mongo_db:27017/n8n?authSource=admin
      - REDIS_HOST=n8n_redis_cache
      - REDIS_PORT=6379
      - REDIS_PASSWORD=outraSenhaForte456
      - REDIS_ENABLE=true
      - N8N_LOG_LEVEL=info
      - N8N_LOG_OUTPUT=stdout
    restart: unless-stopped
    networks:
      - assistant_network

  n8n_mongo_db:
    image: mongo:latest
    container_name: n8n_mongo_db_data
    restart: unless-stopped
    ports:
      - "27017:27017"
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=minhaSenhaForte123 # TROQUE POR UMA SENHA FORTE!
    volumes:
      - n8n_mongo_data:/data/db
    networks:
      - assistant_network

  n8n_redis_cache:
    image: redis:latest
    container_name: n8n_redis_cache_data
    restart: unless-stopped
    command: redis-server --requirepass outraSenhaForte456
    volumes:
      - n8n_redis_data:/data
    networks:
      - assistant_network

  redis_gui:
    image: redislabs/redisinsight:1.14.0
    container_name: redis_gui_client
    ports:
      - "8001:8001"
    volumes:
      - redisinsight_data:/db
    networks:
      - assistant_network
    restart: unless-stopped

  elasticsearch_log:
    image: docker.elastic.co/elasticsearch/elasticsearch:8.11.4
    environment:
      - discovery.type=single-node
      - xpack.security.enabled=false
      - ES_JAVA_OPTS=-Xms512m -Xmx512m
    ulimits:
      memlock:
        soft: -1
        hard: -1
    volumes:
      - elasticsearch_data:/usr/share/elasticsearch/data
    ports:
      - "9200:9200"
    restart: unless-stopped
    networks:
      - assistant_network
    healthcheck:
      test: ["CMD-SHELL", "curl -s http://127.0.0.1:9200 | grep -q 'You Know, for Search'"]
      interval: 10s
      timeout: 10s
      retries: 120

  logstash_processor:
    image: docker.elastic.co/logstash/logstash:8.11.4
    container_name: logstash_processor_data
    volumes:
      - ./logstash:/usr/share/logstash/config:rw
    ports:
      - "5044:5044"
    environment:
      LS_JAVA_OPTS: "-Xms256m -Xmx256m"
      XPACK_MONITORING_ENABLED: "false"
    depends_on:
      elasticsearch_log:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - assistant_network
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "5"

  kibana_viewer:
    image: docker.elastic.co/kibana/kibana:8.11.4
    container_name: kibana_log_viewer
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=["http://elasticsearch_log:9200"]
    depends_on:
      elasticsearch_log:
        condition: service_healthy
    restart: unless-stopped
    networks:
      - assistant_network

  filebeat_shipper:
    image: docker.elastic.co/beats/filebeat:8.11.4
    container_name: filebeat_log_shipper
    user: root
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - /var/lib/docker/containers:/var/lib/docker/containers:ro
      - ./filebeat/filebeat.yml:/usr/share/filebeat/filebeat.yml:ro
    command: ["filebeat", "-e", "-strict.perms=false"]
    depends_on:
      - logstash_processor
    restart: unless-stopped
    networks:
      - assistant_network

volumes:
  n8n_data:
  n8n_mongo_data:
  n8n_redis_data:
  elasticsearch_data:
  redisinsight_data:

networks:
  assistant_network: