version: '3.8'

services:
  n8n:
    image: n8nio/n8n
    ports:
      - "5678:5678"
    volumes:
      - ~/.n8n:/home/node/.n8n
    environment:
      - N8N_HOST=${N8N_HOST:-localhost}
      - N8N_PORT=${N8N_PORT:-5678}
      - N8N_PROTOCOL=${N8N_PROTOCOL:-http}
      - NODE_ENV=production
      - N8N_DB=mongodb # Informa o n8n para usar o MongoDB
      - N8N_DB_MONGODB_URL=mongodb://n8n-mongo:27017/n8n # URL de conexão do MongoDB
      - REDIS_HOST=n8n-redis # Host do Redis para o n8n
    restart: unless-stopped

  n8n-mongo:
    image: mongo:latest
    restart: unless-stopped
    volumes:
      - n8n_mongo_data:/data/db # Volume para persistir os dados do MongoDB

  n8n-redis:
    image: redis:latest
    restart: unless-stopped
    volumes:
      - n8n_redis_data:/data # Volume para persistir os dados do Redis

volumes:
  n8n_mongo_data:
  n8n_redis_data: